src/Blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^',include("Post.urls")),
    url(r'^gallery/',include("Gallery.urls")),
    url(r'^reporter/',include("Reporter.urls")),
    url(r'^instant_articles/',include("Instant_Article.urls")),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^', include("Homepage.urls"))

]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/Homepage/urls.py
from django.conf.urls import url
from . import views


app_name = "Homepage"


urlpatterns = [

    url(r'^$',views.homepage_views,name="home_page"),
]

src/Post/urls.py
from django.conf.urls import url
from . import views

app_name="Post"

urlpatterns = [
    url(r'^category/new_category/$',views.CategoryCreate,name="category_create"),
    url(r'^post/new_post/$',views.PostCreateView,name="add_new_post"),
    url(r'^post/post_list/$',views.PostList,name="post_list"),
    url(r'^(?P<slug>[^/]+)/$',views.PostDetail,name="post_detail"),
    url(r'^category/(?P<category_slug>[^/]+)/$',views.CategoryDetail,name="category_detail"),
    url(r'^(?P<slug>[^/]+)/edit/$',views.PostUpdate,name="post_update"),
    url(r'^(?P<slug>[^/]+)/delete/$',views.PostDetele,name="post_delete"),
    url(r'^about/detail/$',views.about_views,name="about_page"),
    url(r'^contact/detail/$',views.contact_views,name="contact_page"),
    url(r'^privacy-policy/detail/$',views.privacy_views,name="privacy_page"),
    url(r'^advertisements/detail/$',views.advertisements_views,name="ads_page"),


    url('ajax/load-disticts/', views.load_disticts, name='ajax_load_disticts'),  # <-- this one here

]

src/Homepage/models.py
from django.db import models
from Post.models import PostCategory



def upload_location_site_logo(instance, filename):

	return "Site Logo/%s/%s" %(instance.name_of_site,filename)

def upload_location_site_fav(instance, filename):

	return "Site Favicon/%s/%s" %(instance.name_of_site,filename)

class HomepageMiddleSection(models.Model):

	part_one_left		= models.ForeignKey(PostCategory,on_delete=models.CASCADE,default=1,related_name="Left")
	part_two_right 		= models.ForeignKey(PostCategory,on_delete=models.CASCADE,default=1,related_name="Middle")
	ads_code_1			= models.TextField(default="",blank=True)
	ads_code_2 			= models.TextField(default="",blank=True)
	fb_page_code 		= models.TextField(default="",blank=True,help_text="You will get page plugin from <a href='https://developers.facebook.com/docs/plugins/page-plugin/' target='_blank'>here.</a>")



	def __str__(self):

		return "Middle Widget"

class InsertHeaderFooter(models.Model):


	header_code 		= models.TextField(default="",blank=True)
	footer_code 		= models.TextField(default="",blank=True)


	def __str__(self):

		return "Insert Header & Footer"

class HomepageMiddleSectionBelow(models.Model):

	part_one 			= models.ForeignKey(PostCategory,on_delete=models.CASCADE,default=1)


	def __str__(self):

		return "Middle Widget Below"

class HomepageMiddleSectionBelowTwo(models.Model):

	part_one_two 			= models.ForeignKey(PostCategory,on_delete=models.CASCADE,default=1)


	def __str__(self):

		return "Middle Widget Below Two"

class FooterAboveSection(models.Model):

	footer_above_1			= models.ForeignKey(PostCategory,on_delete=models.CASCADE,default=1,related_name="footer_above_1")
	footer_above_2			= models.ForeignKey(PostCategory,on_delete=models.CASCADE,default=1,related_name="footer_above_2")
	footer_above_3			= models.ForeignKey(PostCategory,on_delete=models.CASCADE,default=1,related_name="footer_above_3")
	footer_above_4			= models.ForeignKey(PostCategory,on_delete=models.CASCADE,default=1,related_name="footer_above_4")


	def __str__(self):

		return "Footer Above Section"

class GeneralSettings(models.Model):

	name_of_site 			= models.CharField(max_length=200,blank=True)
	site_tag_line			= models.CharField(max_length=200,blank=True)
	site_logo				= models.ImageField(upload_to=upload_location_site_logo,
                                null=True,
                                blank=True,
                                width_field="width_field",
                                height_field="height_field")
	height_field        	= models.IntegerField(default=0)
	width_field         	= models.IntegerField(default=0)
	site_favicon			= models.ImageField(upload_to=upload_location_site_fav,
                                null=True,
                                blank=True,
                                width_field="height_field_fav",
                                height_field="width_field_fav")
	height_field_fav        = models.IntegerField(default=32)
	width_field_fav         = models.IntegerField(default=32)

	def __str__(self):
		return str(self.name_of_site)


class HomepageAds(models.Model):

	header_ads_970x90		= models.TextField(default="",blank=True)
	sidebar_1				= models.TextField(default="",blank=True)
	sidebar_2				= models.TextField(default="",blank=True)
	sidebar_3				= models.TextField(default="",blank=True)

	def __str__(self):

		return "Homepage Ads"

class PostDetailPageAds(models.Model):

	left_sidebar_160x900	= models.TextField(default="",blank=True)
	right_sidebar_1			= models.TextField(default="",blank=True)
	right_sidebar_2			= models.TextField(default="",blank=True)
	right_sidebar_3			= models.TextField(default="",blank=True)
	before_post				= models.TextField(default="",blank=True)
	after_post				= models.TextField(default="",blank=True)

	def __str__(self):

		return "Post Detail Ads"

class CopyRightSection(models.Model):

	copy_right_text			= models.TextField(default="",blank=True)
	about_summary			= models.TextField(default="",blank=True)
	about_full				= models.TextField(default="",blank=True)
	editor_email			= models.CharField(max_length=250,default="",blank=True)
	privary_policy			= models.TextField(default="",blank=True)
	conatct					= models.TextField(default="",blank=True)
	advertisement			= models.TextField(default="",blank=True)


	def __str__(self):

		return "Copyright Section"


class SEO(models.Model):

	facebook_app_id			= models.CharField(max_length=200,verbose_name = "Facebook App ID",default="",blank=True)
	facebook_page_id		= models.CharField(max_length=200,verbose_name = "Facebook Page ID",default="",blank=True)
	meta_description		= models.TextField(default="",verbose_name="Meta Description",blank=True)
	domain_name				= models.CharField(max_length=200,verbose_name = "Domain Name",default="",blank=True)
	site_title				= models.CharField(max_length=200,verbose_name = "Site Title",default="",blank=True)


	def __str__(self):

		return "SEO"

src/Homepage/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from django.http import Http404
from Post.models import PostModel,PostCategory,DivisionalPostCategory
from Gallery.models import ImageGallery
from .models import (
					HomepageMiddleSection,
					InsertHeaderFooter,
					HomepageMiddleSectionBelow,
					HomepageMiddleSectionBelowTwo,
					FooterAboveSection,
					GeneralSettings,
					HomepageAds,
					CopyRightSection,
					SEO
					)
from Instant_Article.models import InstantArticleModel


def CategorySlice(category_query):
	# This function will split the all category into two parts.
	category_list = []
	for i in category_query:
		category_list.append(i.category_name)
		half = len(category_list)//2
	return category_list[:half],category_list[half:]




def homepage_views(request):

	# try:



		latest_post					= PostModel.objects.all()[:6] # Last 6 Posts
		all_category				= PostCategory.objects.all() # All category
		all_posts 					= PostModel.objects.all() # All Posts
		all_images 					= ImageGallery.objects.all() # All Images
		middle_section 				= HomepageMiddleSection.objects.all() # All Selected Middle Section Category
		middle_left_category 		= PostCategory.objects.get(category_name=middle_section[0].part_one_left) # Middle left category name
		middle_right_category 		= PostCategory.objects.get(category_name=middle_section[0].part_two_right)# Middle right(center) category name
		middle_left_all_post 		= PostModel.objects.filter(category=middle_left_category)[1:4] # Middle left category posts (last 3 posts without first post)
		middle_left_first_post 		= PostModel.objects.filter(category=middle_left_category)[0] # Middle left category latest post
		middle_right_all_post 		= PostModel.objects.filter(category=middle_right_category)[1:4] # Middle right(center) posts.
		middle_right_first_post 	= PostModel.objects.filter(category=middle_right_category)[0] # Middle right(center) latest post.
		middle_ads_code				= HomepageMiddleSection.objects.all()[0] # Middle section ads code.Show in right.
		header_footer_code 			= InsertHeaderFooter.objects.all()[0] # Header and Footer Code
		middle_section_below		= HomepageMiddleSectionBelow.objects.all() # Section immediate below of middle section.Get that category.
		middle_section_below_posts	= PostModel.objects.filter(category=middle_section_below[0].part_one)[1:5] # All posts of selected section of immediate below of middle.Latest 4 posts(without last post)
		middle_section_below_posts_1= PostModel.objects.filter(category=middle_section_below[0].part_one)[0] # Thats the latest post.
		middle_section_below_cat	= PostCategory.objects.get(category_name=middle_section_below[0].part_one) # Category name of immediate below of middle.
		middle_below_two			= HomepageMiddleSectionBelowTwo.objects.all() # Third middle section category.
		middle_below_two_post		= PostModel.objects.filter(category=middle_below_two[0].part_one_two)[1:7] # Third middle section posts
		middle_below_two_post_1		= PostModel.objects.filter(category=middle_below_two[0].part_one_two)[0] # Third middle section clatest post.
		middle_below_two_cat 		= PostCategory.objects.get(category_name=middle_below_two[0].part_one_two) # Third middle section category name.
		footer_above				= FooterAboveSection.objects.all() # footer category
		footer_above_cat_1_name		= PostCategory.objects.get(category_name=footer_above[0].footer_above_1) # Footer 1 category name
		footer_above_1_posts		= PostModel.objects.filter(category=footer_above_cat_1_name)[:4] # Footer 1 posts.
		footer_above_cat_2_name		= PostCategory.objects.get(category_name=footer_above[0].footer_above_2) # Footer 2 category name
		footer_above_2_posts		= PostModel.objects.filter(category=footer_above_cat_2_name)[:4] # Footer 2 posts.
		footer_above_cat_3_name		= PostCategory.objects.get(category_name=footer_above[0].footer_above_3) # Footer 3 category name
		footer_above_3_posts		= PostModel.objects.filter(category=footer_above_cat_3_name)[:4] # Footer 3 posts.
		footer_above_cat_4_name		= PostCategory.objects.get(category_name=footer_above[0].footer_above_4) # Footer 4 category name
		footer_above_4_posts		= PostModel.objects.filter(category=footer_above_cat_4_name)[:4] # Footer 4 posts.
		general_settings			= GeneralSettings.objects.all()[0]
		most_popular				= PostModel.objects.all().order_by("-total_page_views")
		ads_homepage				= HomepageAds.objects.all()[0]
		copyright_info				= CopyRightSection.objects.all()[0]
		seo 						= SEO.objects.all()[0]
		google_analytics 			= InstantArticleModel.objects.all()[0]


		'''
		This is the value of all category which is
		divided into two parts first.Then each of
		that parts are again divided into two parts.
		Thus, we have divided the catgory into 4 parts.
		'''

		category_1st_half,category_2nd_half = CategorySlice(all_category)
		category_1st_half_1st = category_1st_half[:len(category_1st_half)//2]
		category_1st_half_2nd = category_1st_half[len(category_1st_half)//2:]
		category_2nd_half_1st = category_2nd_half[:len(category_2nd_half)//2]
		category_2nd_half_2nd = category_2nd_half[len(category_2nd_half)//2:]

		template_name = "Homepage/index.html"
		context ={

				"latest_post":latest_post,
				"all_posts":all_posts,
				"all_images":all_images,
				"all_category":all_category,
				"middle_section":middle_section,
				"middle_left_category":middle_left_category,
				"middle_right_category":middle_right_category,
				"middle_left_all_post":middle_left_all_post,
				"middle_left_first_post":middle_left_first_post,
				"middle_right_all_post":middle_right_all_post,
				"middle_right_first_post":middle_right_first_post,
				"middle_ads_code":middle_ads_code,
				"header_footer_code":header_footer_code,
				"middle_section_below_posts":middle_section_below_posts,
				"middle_section_below_posts_1":middle_section_below_posts_1,
				"middle_section_below_cat":middle_section_below_cat,
				"middle_below_two_post":middle_below_two_post,
				"middle_below_two_post_1":middle_below_two_post_1,
				"middle_below_two_cat":middle_below_two_cat,
				"footer_above_cat_1_name":footer_above_cat_1_name,
				"footer_above_1_posts":footer_above_1_posts,
				"footer_above_cat_2_name":footer_above_cat_2_name,
				"footer_above_2_posts":footer_above_2_posts,
				"footer_above_cat_3_name":footer_above_cat_3_name,
				"footer_above_3_posts":footer_above_3_posts,
				"footer_above_cat_4_name":footer_above_cat_4_name,
				"footer_above_4_posts":footer_above_4_posts,
				"category_1st_half_1st":category_1st_half_1st,
				"category_1st_half_2nd":category_1st_half_2nd,
				"category_2nd_half_1st":category_2nd_half_1st,
				"category_2nd_half_2nd":category_2nd_half_2nd,
				"general_settings":general_settings,
				"most_popular":most_popular,
				"ads_homepage":ads_homepage,
				"copyright_info":copyright_info,
				"seo":seo,
				"google_analytics":google_analytics
		}

		return render(request,template_name,context)

	# except:
	# 	raise Http404

src/templates/Homepage/adsvertisements.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ general_settings.name_of_site }} | বিজ্ঞাপন</title>

    {% include "Homepage/header.html" %}

</head>

<body>


    <!-- header social icon start -->
    <div class="header_social_icon">
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <div class="date">
                        <p><i class="fas fa-map-marker-alt"></i>  ঢাকা, <script type="text/javascript" src="http://english-date.appspot.com/index5.php"></script> | <script type="text/javascript" src="http://bangladate.appspot.com/index5.php"></script></p>
                    </div>
                </div>
                <div class="col-sm-4 hidden-xs">
                    <div class="social_icon">
                        <ul>
                            <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                            <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                            <li><a href="#"><i class="fab fa-youtube"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clr"></div>
    <!-- header social icon end -->

    <!-- Menubar start -->

    <nav class="navbar navbar-default custom_nav">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my_nav" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="logo">
                    {% if general_settings.site_logo %}
                    <a href="/"><img src="{{ general_settings.site_logo.url }}" alt="logo" width="190px"></a>
                    {% else %}
                        Site Logo
                    {% endif %}
                </div>
            </div>

            <div class="collapse navbar-collapse" id="my_nav">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/">মূলপাতা</a></li>
                    {% for ob in all_category %}
                    <li><a href="{% url "Post:category_detail" ob.category_slug %}">{{ ob.category_name }}</a></li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </nav>

    <!-- Menubar end -->


    <div class="latest_news_scroll">
        <div class="container">
            <div class="row">
                <div class="mlr">
                    <div>
                    {% if ads_homepage.header_ads_970x90 %}
                        {{ ads_homepage.header_ads_970x90|safe }}
                    {% else %}
                    <img src="{% static "img/ads_970x90.jpg" %}" width="100%" style="margin-top: 10px;" alt="970x90">
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Details part start -->
    <section class="details">
              <div class="latest_news_scroll">
                  <div class="container">
                      <div class="row">
                          <div class="mlr" style="text-align: justify;">
                            {% for ob in about_string|slice:":1"%}
                              <font size="4">{{ ob.advertisement|safe}}</font>
                            {% endfor %}
                          </div>
                      </div>
                  </div>
              </div>
    </section>
    <!-- Details part end -->

	<!-- Footer part start -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-12 footer_logo">
                    <a href="#" class="name_plate">{{ general_settings.name_of_site }} </a>
                </div>
                <div class="col-md-2 col-sm-3 col-xs-6">
                {% for ob in category_1st_half_1st %}
                    {% for ob2 in all_category %}
                        {% if ob2.category_name == ob %}
                            <a href="{% url "Post:category_detail" ob2.category_slug %}">{{ ob2.category_name }}</a>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
                </div>

                <div class="col-md-2 col-sm-3 col-xs-6">
                {% for ob in category_1st_half_2nd %}
                    {% for ob2 in all_category %}
                        {% if ob2.category_name == ob %}
                            <a href="{% url "Post:category_detail" ob2.category_slug %}">{{ ob2.category_name }}</a>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
                </div>
                <div class="col-md-2 col-sm-3 col-xs-6">
                {% for ob in category_2nd_half_1st %}
                    {% for ob2 in all_category %}
                        {% if ob2.category_name == ob %}
                            <a href="{% url "Post:category_detail" ob2.category_slug %}">{{ ob2.category_name }}</a>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
                </div>

                <div class="col-md-2 col-sm-3 col-xs-6">
                {% for ob in category_2nd_half_2nd %}
                    {% for ob2 in all_category %}
                        {% if ob2.category_name == ob %}
                            <a href="{% url "Post:category_detail" ob2.category_slug %}">{{ ob2.category_name }}</a>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
                </div>
                <div class="clr visible-sm visible-xs"></div>
                <div class="col-md-4">
                    <div class="about_us">
                      {% if copyright_info.about_summary %}
                      <p>{{ copyright_info.about_summary|safe }}</p>
                      {% else %}
                      <p>About Website</p>
                      {% endif %}
                      {% if copyright_info.editor_email %}
                      <p>সম্পাদকঃ {{ copyright_info.editor_email|safe }}</p>
                      {% else %}
                      <p>ইমেইলঃ info@website.com</p>
                      {% endif %}
                        <ul>
                            <li><a href="#"><i class="fab fa-facebook" style="color: #4267b2"></i></a></li>
                            <li><a href="#"><i class="fab fa-twitter-square" style="color: #1da1f2"></i></a></li>
                            <li><a href="#"><i class="fab fa-linkedin" style="color: #4267b2"></i></a></li>
                            <li><a href="#"><i class="fab fa-pinterest" style="color: #bd081c"></i></a></li>
                            <li><a href="#"><i class="fab fa-youtube" style="color: #bd081c"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer part end -->
    <div class="copyright">
      <p>
        <a href="{% url "Post:about_page" %}" style="color:white;">আমাদের সম্পর্কে</a> | <a href="{% url "Post:contact_page" %}" style="color:white;">যোগাযোগ</a> | <a href="{% url "Post:privacy_page" %}" style="color:white;">গোপনীয় নিতিমালা</a> | <a href="{% url "Post:ads_page" %}" style="color:white;">বিজ্ঞাপন</a>
      </p>
      <p>
        {% if copyright_info.copy_right_text %}
        {{ copyright_info.copy_right_text|safe }}
        {% else %}
        Copyrigth@2018 | Website.Com
        {% endif %}
      </p>
      <p>
        কারিগরি সহযোগিতায় <a href="https://www.facebook.com/rasel.cse07" target="_blank" style="color:green;">মোঃ রাসেল</a>
      </p>
    </div>



    <!-- ================== back to top start ================== -->

    <div class="back_to_top">
        <a href="#" class="go-top"><i class="fa fa-angle-up"></i></a>
    </div>

    <!--  ================== back to top end ================== -->




{% include "Homepage/footer.html" %}


</body>

</html>

src/templates/Homepage/footer.html
{% load static %}
<!-- jQuery Library -->
<script src="{% static "Base/js/jquery-1.12.4.min.js" %}"></script>
<!-- Bootstrap js -->
<script src="{% static "Base/js/bootstrap.min.js" %}"></script>
<!-- Slick Slider -->
<script src="{% static "Base/js/slick.min.js" %}"></script>
<!-- Venubox -->
<script src="{% static "Base/js/venobox.min.js" %}"></script>
<!-- Mains Custom js -->
<script src="{% static "Base/js/custom.js" %}"></script>
<!-- Footer Code -->
{{ header_footer_code.footer_code|safe }}

src/templates/Homepage/header.html
{% load static %}

<link rel="shortcut icon" type="image/png" href="{{ general_settings.site_favicon.url }}"/>

<!-- Bootstrap -->
<link href="{% static "Base/css/bootstrap.min.css" %}" rel="stylesheet">

<!-- Fontawesome -->
<script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>

<!-- jQuery Plugins css -->
<link href="{% static "Base/css/slick.css" %}" rel="stylesheet">
<link href="css/venobox.css" rel="stylesheet">

<!-- Main Css -->
<link rel="stylesheet" href="{% static "Base/css/style.css" %}">
<link rel="stylesheet" href="{% static "Base/css/responsive.css" %}">

<!-- Insert Header -->
{{ header_footer_code.header_code|safe }}
    
<style type="text/css">
        #top-left {
        position: absolute;
        top: 8px;
        left: 16px;
        margin-left: 10px;

</style>