src/Blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^',include("Post.urls")),
    url(r'^gallery/',include("Gallery.urls")),
    url(r'^reporter/',include("Reporter.urls")),
    url(r'^instant_articles/',include("Instant_Article.urls")),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^', include("Homepage.urls"))

]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/Gallery/urls.py
from django.conf.urls import url
from . import views

app_name="Gallery"

urlpatterns = [
    url(r'^upload_images/$',views.ImageUpload,name="upload_image"),

]

src/Post/urls.py
from django.conf.urls import url
from . import views

app_name="Post"

urlpatterns = [
    url(r'^category/new_category/$',views.CategoryCreate,name="category_create"),
    url(r'^post/new_post/$',views.PostCreateView,name="add_new_post"),
    url(r'^post/post_list/$',views.PostList,name="post_list"),
    url(r'^(?P<slug>[^/]+)/$',views.PostDetail,name="post_detail"),
    url(r'^category/(?P<category_slug>[^/]+)/$',views.CategoryDetail,name="category_detail"),
    url(r'^(?P<slug>[^/]+)/edit/$',views.PostUpdate,name="post_update"),
    url(r'^(?P<slug>[^/]+)/delete/$',views.PostDetele,name="post_delete"),
    url(r'^about/detail/$',views.about_views,name="about_page"),
    url(r'^contact/detail/$',views.contact_views,name="contact_page"),
    url(r'^privacy-policy/detail/$',views.privacy_views,name="privacy_page"),
    url(r'^advertisements/detail/$',views.advertisements_views,name="ads_page"),


    url('ajax/load-disticts/', views.load_disticts, name='ajax_load_disticts'),  # <-- this one here

]

src/Post/models.py
from datetime import timedelta, datetime, date
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.encoding import smart_text
from django.utils.safestring import mark_safe
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.timesince import timesince
from .utils import (
                    unique_category_slug_generator,
                    unique_post_slug_generator,
                    unique_divisional_category_slug_generator
                    )

from Gallery.models import ImageGallery

POST_PUBLISH=[
        ("draft","Draft"),
        ("publish","Publish"),
        ("private","Private")
]



FEATURED_POST=[
        
        ("Y","Yes"),
        ("N","No")
        
]


class DivisionName(models.Model):

    division_name       = models.CharField(max_length=200)

    def __str__(self):
        return smart_text(self.division_name)




class PostCategory(models.Model):

    category_name       = models.CharField(max_length=250)
    category_slug       = models.CharField(max_length=250,unique=True,db_index = True)


    class Meta:

        verbose_name='General Category'
        verbose_name_plural='General Category'

    def __str__(self):
        return smart_text(self.category_name)


class DivisionalPostCategory(models.Model):

    name_of_division             = models.ForeignKey(DivisionName,on_delete=models.CASCADE)
    name_of_distict              = models.CharField(max_length=100)
    divisional_category_slug     = models.CharField(max_length=250,unique=True,db_index = True)



    class Meta:

        verbose_name="Divisional Post Category"
        verbose_name_plural="Divisional Post Category"
        ordering=["name_of_distict"]

    def __str__(self):

        return smart_text(self.name_of_distict)

class PostModel(models.Model):

    user                = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title               = models.CharField(max_length=250)
    slug                = models.CharField(max_length=250,unique=True,db_index = True)
    category            = models.ForeignKey(PostCategory,on_delete=models.CASCADE)
    content             = models.TextField()
    featured_image_id   = models.CharField(max_length=250)
    publish_date        = models.DateField(auto_now=False, auto_now_add=False, default=timezone.now)
    publish             = models.CharField(max_length=100,choices=POST_PUBLISH,default="publish")
    timestamp           = models.DateTimeField(auto_now=False,auto_now_add=True)
    updated             = models.DateTimeField(auto_now=True,auto_now_add=False)
    is_featured         = models.CharField(max_length=100,choices=FEATURED_POST,default="N")
    division            = models.ForeignKey(DivisionName,on_delete=models.CASCADE,blank=True,null=True)
    divisional_category = models.ForeignKey(DivisionalPostCategory,on_delete=models.CASCADE,blank=True,null=True)
    is_image_gallery    = models.CharField(max_length=200,choices=FEATURED_POST,default="N") 
    is_video_gallery    = models.CharField(max_length=200,choices=FEATURED_POST,default="N") 
    total_page_views    = models.IntegerField(default=0)

    class Meta:

        verbose_name='Post'
        verbose_name_plural='Posts'
        ordering=["-timestamp","-updated"]

    def __str__(self):

        return smart_text(self.title)

    def get_absolute_url(self):

        return reverse("Post:post_detail", kwargs={"slug": self.slug})

    @property
    def get_markdown(self):
        content = self.content
        # markdown_text = markdown(content)
        return mark_safe(content)

    @property
    def age(self):
        if self.publish == 'publish':
            now = datetime.now()
            publish_time = datetime.combine(
                                self.publish_date,
                                datetime.now().min.time()
                        )
            try:
                difference = now - publish_time
            except:
                return "Unknown"
            if difference <= timedelta(minutes=1):
                return 'just now'
            return '{time} ago'.format(time= timesince(publish_time).split(', ')[0])
        return "Not published"




def category_pre_save_receiver(sender,instance,*args,**kwargs):

    if not instance.category_slug:

        instance.category_slug=unique_category_slug_generator(instance)


def divisional_category_pre_save_receiver(sender,instance,*args,**kwargs):

    if not instance.divisional_category_slug:

        instance.divisional_category_slug=unique_divisional_category_slug_generator(instance)


def post_pre_save_receiver(sender,instance,*args,**kwargs):

    if not instance.slug:

        instance.slug=unique_post_slug_generator(instance)

pre_save.connect(post_pre_save_receiver, sender=PostModel)
pre_save.connect(category_pre_save_receiver, sender=PostCategory)
pre_save.connect(divisional_category_pre_save_receiver, sender=DivisionalPostCategory)

src/Post/views.py
from datetime import timedelta, datetime, date
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import (
                    CategoryCreateForm,
                    PostCreateForm,
                    PostUpdateForm,
                    DivisionalCategoryCreateForm
                    )

from .models import (
                    PostModel,
                    PostCategory,
                    DivisionalPostCategory,
                    DivisionName
                    )
from Gallery.models import ImageGallery
from Reporter.models import Profile
from Homepage.models import (
                            GeneralSettings,
                            InsertHeaderFooter,
                            HomepageMiddleSection,
                            HomepageAds,
                            PostDetailPageAds,
                            CopyRightSection,
                            SEO
                            )
from Homepage.views import CategorySlice
from Instant_Article.models import InstantArticleModel



########################################################################################
#                                   Create views                                       #
########################################################################################

# This method is for ajax call

def load_disticts(request):

    division_id = request.GET.get('division')
    disticts = DivisionalPostCategory.objects.filter(id=division_id)
    return render(request, 'Post/disticts_dropdown_list_options.html', {'disticts': disticts})

def CategoryCreate(request):

    qs = PostCategory.objects.all()
    qs2 = DivisionalPostCategory.objects.all()
    form=CategoryCreateForm(request.POST or None)
    form2 = DivisionalCategoryCreateForm(request.POST or None)

    if form.is_valid() and "general_category" in request.POST:

        instance=form.save(commit=False)
        instance.save()
        messages.success(request, "Category Created", extra_tags='html_safe')

    if form2.is_valid() and "divisonal_category" in request.POST:

        instance=form2.save(commit=False)
        instance.save()
        messages.success(request, "Category Created", extra_tags='html_safe')


    template_name="Post/category_create.html"
    context={
                "form":form,
                "qs":qs,
                "form2":form2,
                "qs2":qs2
            }

    return render(request,template_name,context)

def PostCreateView(request):


    form=PostCreateForm(request.POST or None,request.FILES or None)

    if form.is_valid():


        instance=form.save(commit=False)
        instance.user=request.user
        instance.save()

        messages.success(request, "Post Created", extra_tags='html_safe')
        return HttpResponseRedirect(instance.get_absolute_url() +"edit/")

    template_name="Post/post_create.html"
    context={"form":form}

    return render(request,template_name,context)


#########################################################################################
#                           List & Detail Views                                         #
#########################################################################################

def PostList(request):

    qs=PostModel.objects.all() # Getting all posts
    qs2=ImageGallery.objects.all() # Getting all images
    reporter_name = Profile.objects.all()
    user_post=PostModel.objects.filter(user=request.user)
    page = request.GET.get('page', 1)

    paginator = Paginator(qs, 10)


    try:
        posts_qs = paginator.page(page)
    except PageNotAnInteger:
        posts_qs = paginator.page(1)
    except EmptyPage:
        posts_qs = paginator.page(paginator.num_pages)


    template_name="Post/post_list.html"
    context={

                "posts_qs":posts_qs,
                "qs2":qs2,
                "qs":qs,
                "reporter_name":reporter_name,
                "user_post":user_post
            }

    return render(request,template_name,context)

def PostDetail(request,slug=None):

    qs                  = get_object_or_404(PostModel,slug=slug)
    category_qs         = get_object_or_404(PostCategory,category_name=qs.category)
    featured_image_qs   = get_object_or_404(ImageGallery,image_id=qs.featured_image_id)
    qs.total_page_views += 1
    qs.save()
    total_hit           = qs.total_page_views
    general_settings    = GeneralSettings.objects.all()[0]
    header_footer_code  = InsertHeaderFooter.objects.all()[0] # Header and Footer Code
    all_category        = PostCategory.objects.all() # All category
    reporter            = Profile.objects.get(username=qs.user)
    middle_ads_code     = HomepageMiddleSection.objects.all()[0] # Middle section ads code.Show in right.
    all_posts           = PostModel.objects.all() # All Posts
    most_popular        = PostModel.objects.all().order_by("-total_page_views")
    all_images          = ImageGallery.objects.all() # All Images
    ads_homepage        = HomepageAds.objects.all()[0]
    post_detail_ads     = PostDetailPageAds.objects.all()[0]
    copyright_info		= CopyRightSection.objects.all()[0]
    seo                 = SEO.objects.all()[0]
    google_analytics 	= InstantArticleModel.objects.all()[0]


    '''
    This is the value of all category which is
    divided into two parts first.Then each of
    that parts are again divided into two parts.
    Thus, we have divided the catgory into 4 parts.
    '''

    category_1st_half,category_2nd_half = CategorySlice(all_category)
    category_1st_half_1st = category_1st_half[:len(category_1st_half)//2]
    category_1st_half_2nd = category_1st_half[len(category_1st_half)//2:]
    category_2nd_half_1st = category_2nd_half[:len(category_2nd_half)//2]
    category_2nd_half_2nd = category_2nd_half[len(category_2nd_half)//2:]



    template_name="Post/post_detail.html"


    context={
                "qs":qs,
                "category_qs":category_qs,
                "featured_image_qs":featured_image_qs,
                "total_hit":total_hit,
                "general_settings":general_settings,
                "header_footer_code":header_footer_code,
                "all_category":all_category,
                "category_1st_half_1st":category_1st_half_1st,
                "category_1st_half_2nd":category_1st_half_2nd,
                "category_2nd_half_1st":category_2nd_half_1st,
                "category_2nd_half_2nd":category_2nd_half_2nd,
                "reporter":reporter,
                "middle_ads_code":middle_ads_code,
                "all_posts":all_posts,
                "most_popular":most_popular,
                "all_images":all_images,
                "ads_homepage":ads_homepage,
                "post_detail_ads":post_detail_ads,
                "copyright_info":copyright_info,
                "seo":seo,
                "google_analytics":google_analytics


            }

    return render(request,template_name,context)

def CategoryDetail(request,category_slug=None):

    qs                      = get_object_or_404(PostCategory,category_slug=category_slug)
    post_qs                 = PostModel.objects.filter(category__category_name__exact=qs.category_name)
    featured_image_qs       = ImageGallery.objects.all()
    header_footer_code      = InsertHeaderFooter.objects.all()[0] # Header and Footer Code
    general_settings        = GeneralSettings.objects.all()[0]
    all_category            = PostCategory.objects.all() # All category
    all_posts               = PostModel.objects.all() # All Posts
    most_popular            = PostModel.objects.all().order_by("-total_page_views")
    ads_homepage            = HomepageAds.objects.all()[0],
    copyright_info		    = CopyRightSection.objects.all()[0]
    seo                     = SEO.objects.all()[0]
    google_analytics 	    = InstantArticleModel.objects.all()[0]



    page = request.GET.get('page', 1)

    paginator = Paginator(post_qs, 18)


    try:
        paginator_qs = paginator.page(page)
    except PageNotAnInteger:
        paginator_qs = paginator.page(1)
    except EmptyPage:
        paginator_qs = paginator.page(paginator.num_pages)


    '''
    This is the value of all category which is
    divided into two parts first.Then each of
    that parts are again divided into two parts.
    Thus, we have divided the catgory into 4 parts.
    '''

    category_1st_half,category_2nd_half = CategorySlice(all_category)
    category_1st_half_1st               = category_1st_half[:len(category_1st_half)//2]
    category_1st_half_2nd               = category_1st_half[len(category_1st_half)//2:]
    category_2nd_half_1st               = category_2nd_half[:len(category_2nd_half)//2]
    category_2nd_half_2nd               = category_2nd_half[len(category_2nd_half)//2:]

    template_name="Post/category_detail.html"
    context={
                "qs":qs,
                "post_qs":post_qs,
                "featured_image_qs":featured_image_qs,
                "header_footer_code":header_footer_code,
                "general_settings":general_settings,
                "all_category":all_category,
                "category_1st_half_1st":category_1st_half_1st,
                "category_1st_half_2nd":category_1st_half_2nd,
                "category_2nd_half_1st":category_2nd_half_1st,
                "category_2nd_half_2nd":category_2nd_half_2nd,
                "paginator_qs":paginator_qs,
                "all_posts":all_posts,
                "most_popular":most_popular,
                "ads_homepage":ads_homepage,
                "copyright_info":copyright_info,
                "seo":seo,
                "google_analytics":google_analytics

            }

    return render(request,template_name,context)

src/templates/Post/disticts_dropdown_list_options.html
<option value="">---------</option>
{% for ob in disticts %}
<option value="{{ ob.pk }}">{{ ob.name_of_distict }}</option>
{% endfor %}

src/templates/Post/post_list.html
{% extends "Reporter/dashboard.html" %}
{% block content %}
<!-- Start-->
{% if messages %}
   {% for message in messages %}
      <div class="alert  alert-danger alert-dismissible fade show" role="alert">
         <span class="badge badge-pill badge-success">Deleted!</span> {% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}.
         <button type="button" class="close" data-dismiss="alert" aria-label="Close">
         <span aria-hidden="true">&times;</span>
         </button>
      </div>
   {% endfor %}
{% endif %}
<div class="col-xl-12">
   <div class="card">
      <div class="card-body">
         <div class="row">
            <div class="col-sm-6">
               <h2 class="card-title mb-0">Posts&ensp;&ensp;&ensp;<a href="{% url "Post:add_new_post" %}" class="btn btn-info">Add New</a> </h2>
               <p style="color:blue;">
                  All({{ qs.count }}) | Mine({{ user_post.count }})
               </p>
            </div>
            <!--/.col-->
         </div>
         <!--/.row-->
         <hr>
         <div class="chart-wrapper mt-4" >
            <div class="row">
               <div class="col-sm-12">
                  <table class="table table-bordered">
                     <thead>
                        <tr>
                           <th>Title</th>
                           <th>Author</th>
                           <th>Category</th>
                           <th>Time</th>
                           <th>Updated</th>
                           <th>Featured</th>
                           <th>Divisional Category</th>
                           <th>Images</th>
                        </tr>
                     </thead>
                     <tbody>
                        {% for ob in posts_qs %}
                        <tr>
                           <td>
                              <p>
                                 <a href="{% url "Post:post_update" ob.slug %}">{{ ob.title}}</a>
                              </p>
                              <p>
                                 <a href="{% url "Post:post_update" ob.slug %}" style="color:green;"><i class="fa fa-edit"></i></a> | <a href="{% url "Post:post_delete" ob.slug %}" style="color: red;"><i class="ti-trash"></i></a>
                              </p>
                           </td>
                           <td>
                              {% for author in reporter_name %}
                              {% if ob.user == author.username %}
                              {% if author.display_name %}
                              {{ author.display_name }}
                              {% else %}
                              No Name
                              {% endif %}
                              {% endif %}
                              {% endfor %}
                           </td>
                           <td>{{ ob.category}}</td>
                           <td>{{ ob.timestamp }}</td>
                           <td>{{ ob.updated }}</td>
                           <td>{{ ob.is_featured }}</td>
                           <td>{{ ob.divisional_category }}</td>
                           <td>
                              {% for posts_qs in qs2 %}
                              {% if ob.featured_image_id == posts_qs.image_id %}
                              <img src="{{ posts_qs.upload_image.url }}" height="50px" width="50px">
                              {% endif %}
                              {% endfor %}
                           </td>
                        </tr>
                        {% endfor %}
                     </tbody>
                     {% if posts_qs.has_other_pages %}
                     <ul class="pagination">
                        {% if posts_qs.has_previous %}
                        <li><a href="?page={{ posts_qs.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in posts_qs.paginator.page_range %}
                        {% if posts_qs.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if posts_qs.has_next %}
                        <li><a href="?page={{ posts_qs.next_page_number }}">&raquo;</a></li>
                        {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                     </ul>
                     {% endif %}
                  </table>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End -->
{% endblock %}

src/templates/Post/post_update.html
{% extends "Reporter/dashboard.html" %}
{% block content %}
<style type="text/css">
   input[type=text], select, textarea {
   width: 100%;
   padding: 12px;
   border: 1px solid #ccc;
   border-radius: 4px;
   resize: vertical;
   }
</style>
<!-- Start--> 
{% if messages %}
{% for message in messages %}
<div class="alert  alert-success alert-dismissible fade show" role="alert">
   <span class="badge badge-pill badge-success">Success!</span> {% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}.To view post <a href="{% url "Post:post_detail" qs.slug %}" target="_blank">Click here.</a>
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
   <span aria-hidden="true">&times;</span>
   </button>
</div>
{% endfor %}
{% endif %}
<div class="col-xl-12">
   <div class="card">
      <div class="card-body">
         <div class="row">
            <div class="col-sm-6">
               <h2 class="card-title mb-0">Edit Post&ensp;&ensp;&ensp;<a href="{% url "Post:add_new_post" %}" class="btn btn-info">Add New</a> </h2>
            </div>
            <!--/.col-->
         </div>
         <!--/.row-->
         <hr>
         <div class="chart-wrapper mt-4" >
            <form method='POST' action='' enctype='multipart/form-data' id="postForm" data-disticts-url="{% url "Post:ajax_load_disticts" %}" novalidate>
               {% csrf_token %}
               <div class="form-group">
                  <!-- Start Form Group-->
                  <div class="row">
                     <!-- Start Row -->
                     <div class="col-sm-8">
                        <!-- Left -->
                        <div class="row">
                           <!-- Title -->
                           <div class="col-sm-12">
                              <h2>{{ form.title.label }}</h2>
                              <hr>
                              {{ form.title }}
                           </div>
                        </div>
                        <!-- End Title -->
                        <br>
                        <div class="row">
                           <!-- Content -->
                           <div class="col-sm-12">
                              <h2>{{ form.content.label }}</h2>
                              <hr>
                              {{ form.content }}
                           </div>
                        </div>
                        <!-- End Content -->
                     </div>
                     <!-- End Left -->
                     <div class="col-sm-4">
                        <!-- Right -->
                        <div class="row">
                           <!-- Images Link-->
                           <div class="col-sm-12">
                              <h2>Images Link</h2>
                              <hr>
                              <a data-toggle="modal" href="#myModal" class="btn btn-success" style="width:100%;">Upload/Select Image</a>
                           </div>
                        </div>
                        <!-- End Images Link-->
                        <br>
                        <div class="row">
                           <!-- Images ID and Feature Images -->
                           <div class="col-sm-12">
                              <h2>{{ form.featured_image_id.label }}</h2>
                              <hr>
                              {{ form.featured_image_id }}
                              <br>
                              <h2>Current Image</h2>
                              <hr>
                              {% if qs.featured_image_id %}
                              <img src="{{ featured_image_qs.upload_image.url }}" height="200px" width="300px"><br>
                              {% else %}
                              No featured image
                              {% endif %}
                           </div>
                        </div>
                        <!-- End Images ID and Feature Images-->
                        <br>
                        <div class="row">
                           <!-- Category -->
                           <div class="col-sm-12">
                             <h2>{{ form.category.label }}</h2>
                              <hr>
                              {{ form.category }}
                              <br><br>
                              <h2>{{ form.is_featured.label }}</h2>
                              <hr>
                              {{ form.is_featured }}
                              <br><br>
                              <h2>{{ form.division.label }}</h2>
                              <hr>
                              {{ form.division }}
                              <br><br>
                              <h2>{{ form.divisional_category.label }}</h2>
                              <hr>
                              {{ form.divisional_category }}
                              <br><br>
                              <h2>{{ form.is_image_gallery.label }}</h2>
                              <hr>
                              {{ form.is_image_gallery }}
                              <br><br>
                              <h2>{{ form.is_video_gallery.label }}</h2>
                              <hr>
                              {{ form.is_video_gallery }}
                              <br><br>
                              <h2>{{ form.publish.label }}</h2>
                              <hr>
                              {{ form.publish }}
                           </div>
                        </div>
                        <!-- End Category-->
                     </div>
                     <!-- End Right -->
                  </div>
                  <!--End Row-->
               </div>
               <!--End Form Group -->
               <br>
               <br>
               <div class="row">
                  <div class="col-sm-12">
                     <input type="submit" value="Publish" class="btn btn-primary btn-lg">
                  </div>
               </div>
            </form>
            <!-- End Body -->                 
            <!-- Modal -->
            <div class="modal fade" id="myModal" role="dialog">
               <div class="modal-dialog modal-lg">
                  <div class="modal-content">
                     <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Featured Image</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                        </button>
                     </div>
                     <div class="modal-body">
                        <div class="embed-responsive embed-responsive-16by9">
                           <iframe id="Right" class="embed-responsive-item" src="{% url "Gallery:upload_image" %}"></iframe>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <!-- End Modal -->
         </div>
      </div>
   </div>
</div>
<!-- End -->

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_division").change(function () {
      var url = $("#postForm").attr("data-disticts-url");  // get the url of the `load_disticts` view
      var divisionID = $(this).val();  // get the selected division ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/post/ajax/load-disticts/)
        data: {
          'division': divisionID       // add the division id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_disticts` view function
          $("#id_divisional_category").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>
  
{% endblock %}