src/Blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^',include("Post.urls")),
    url(r'^gallery/',include("Gallery.urls")),
    url(r'^reporter/',include("Reporter.urls")),
    url(r'^instant_articles/',include("Instant_Article.urls")),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^', include("Homepage.urls"))

]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/Instant_Article/urls.py
from django.conf.urls import url
from .feeds import LatestEntriesFeed

app_name = "Instant_Article"

urlpatterns = [

     url(r'^feed/$', LatestEntriesFeed()),
]

src/Post/urls.py
from django.conf.urls import url
from . import views

app_name="Post"

urlpatterns = [
    url(r'^category/new_category/$',views.CategoryCreate,name="category_create"),
    url(r'^post/new_post/$',views.PostCreateView,name="add_new_post"),
    url(r'^post/post_list/$',views.PostList,name="post_list"),
    url(r'^(?P<slug>[^/]+)/$',views.PostDetail,name="post_detail"),
    url(r'^category/(?P<category_slug>[^/]+)/$',views.CategoryDetail,name="category_detail"),
    url(r'^(?P<slug>[^/]+)/edit/$',views.PostUpdate,name="post_update"),
    url(r'^(?P<slug>[^/]+)/delete/$',views.PostDetele,name="post_delete"),
    url(r'^about/detail/$',views.about_views,name="about_page"),
    url(r'^contact/detail/$',views.contact_views,name="contact_page"),
    url(r'^privacy-policy/detail/$',views.privacy_views,name="privacy_page"),
    url(r'^advertisements/detail/$',views.advertisements_views,name="ads_page"),


    url('ajax/load-disticts/', views.load_disticts, name='ajax_load_disticts'),  # <-- this one here

]

src/Reporter/urls.py
from django.conf.urls import url
from . import views

app_name="Reporter"

urlpatterns = [
	url(r'^enter/$', views.UserLogin,name="user_login"),
	url(r'^logout/$', views.UserLogout,name="user_logout"),
    url(r'^add_new/$', views.Register,name="user_register"),
    url(r'^all_reporters/$', views.AllUsers,name="reporters"),
    url(r'^general_settings/create/$', views.GeneralSettingsCreate,name="general_settings_create"),
    url(r'^general_settings/update/$', views.GeneralSettingsUpdate,name="general_settings_update"),
    url(r'^theme_settings/enable/$', views.ThemeSettingsEnable,name="enable_settings"),
    url(r'^theme_settings/middle_widget/$', views.HomepageMiddleSectionWidget,name="middle_widget"),
    url(r'^theme_settings/middle_widget_below/$', views.HomepageMiddleSectionWidgetBelow,name="middle_widget_below"),
    url(r'^theme_settings/middle_widget_below_two/$', views.HomepageMiddleSectionWidgetBelowTwo,name="middle_widget_below_two"),
    url(r'^theme_settings/insert_header_footer/$', views.InsertHeaderFooterView,name="insert_header"),
    url(r'^footer/above/$', views.FooterAboveSectionView,name="footer_above"),
    url(r'^insatnt_article/$', views.Instant_Articles_Views,name="insatnt_article"),
    url(r'^seo/$', views.SEO_Views,name="seo_settings"),
    url(r'^(?P<user>[A-Za-z0-9].*)/dashboard/$', views.Dashboard,name="user_dashboard"),
    url(r'^(?P<user>[A-Za-z0-9].*)/dashboard/profile/detail/$', views.UserDetail,name="user_detail"),
    url(r'^(?P<user>[A-Za-z0-9].*)/dashboard/profile/edit/$', views.UserUpdate,name="user_update"),
    url(r'^ads/home_section/$', views.HomepageAdsSection,name="homepage_ads"),
	url(r'^ads/post_detail_ads/$', views.PostDetailAdsSection,name="post_detail_ads"),
	url(r'^ads/post_detail_ads/$', views.PostDetailAdsSection,name="post_detail_ads"),
	url(r'^general_settings/copyright/$', views.CopyRight_Section,name="copyright_section"),


]

src/Instant_Article/models.py
from django.db import models
from django.utils.safestring import mark_safe




class InstantArticleModel(models.Model):

	facebook_page_ID		= models.CharField(max_length=200,verbose_name="Facebook Page ID",default="",blank=True)
	article_style			= models.CharField(max_length=200,verbose_name="Article Style",default="",blank=True)
	copyright				= models.CharField(max_length=200,verbose_name="Copyright",default="",blank=True)
	domain_name				= models.CharField(max_length=200,verbose_name="Domain Name",default="",blank=True)
	ads_code				= models.CharField(max_length=200,verbose_name="Ads Code",default="",blank=True)
	google_analytics		= models.TextField(verbose_name="Google Analytics Code",default="",blank=True)


	def __str__(self):

		return "Instant Article"

	@property
	def get_markdown(self):
		content = self.copyright
		return mark_safe(content)

src/Instant_Article/views.py
from django.shortcuts import render

src/Reporter/views.py
from django.contrib.auth import (
								login,
								get_user_model,
								logout
								)
from django.utils.timezone import datetime
from django.contrib import messages
from django.urls import reverse
from django.utils import timezone
from django.shortcuts import (
								render,
								HttpResponseRedirect,
								get_object_or_404
							)
from .forms import (
					UserCreationForm,
					UserLoginForm,
					UserUpdateForm,
					HomepageMiddleWidgetForm,
					InsertHeaderFooterForm,
					HomepageMiddleWidgetFormBelow,
					HomepageMiddleWidgetFormBelowTwo,
					FooterAboveSectionForm,
					GeneralSettingsForm,
					HomepageAdsForm,
					PostDetailAdsForm,
					CopyRightSectionForm,
					InstantArticleModelForm,
					SEOForm
					)

from .models import Profile
from Post.models import PostModel
from Homepage.models import (
							HomepageMiddleSection,
							InsertHeaderFooter,
							HomepageMiddleSectionBelow,
							HomepageMiddleSectionBelowTwo,
							FooterAboveSection,
							GeneralSettings,
							HomepageAds,
							PostDetailPageAds,
							CopyRightSection,
							SEO
							)
from Instant_Article.models import InstantArticleModel



User = get_user_model()





def Register(request,*args,**kwargs):

	form = UserCreationForm(request.POST or None)

	if form.is_valid():

		instance=form.save(commit=False)
		instance.save()
		messages.success(request, "User Created", extra_tags='html_safe')

	template_name="Reporter/register.html"
	context={

				"form":form

			}


	return render(request,template_name,context)


def UserLogin(request,*args,**kwargs):

	if not request.user.is_authenticated():

		form=UserLoginForm(request.POST or None)

		if form.is_valid():

				username_=form.cleaned_data.get("username")
				user_obj=User.objects.get(username__iexact=username_)
				login(request,user_obj)
				return HttpResponseRedirect(user_obj.get_absolute_url)


		template_name="Reporter/login.html"
		context={

				"form":form
				}

		return render(request,template_name,context)
	else:
		username_ = request.user.username
		user_obj = User.objects.get(username__iexact=username_)
		return HttpResponseRedirect(user_obj.get_absolute_url)


def UserLogout(request):

	logout(request)
	return HttpResponseRedirect("/reporter/enter")



def Dashboard(request,user=None):

	# try:

		total_posts 			= PostModel.objects.all() # All Posts
		user_post 				= PostModel.objects.filter(user=request.user) # Users All Post
		user_count 				= User.objects.all() # All Posts
		todays_post 			= PostModel.objects.filter(publish_date__day=datetime.today().day).count() # Todays total posts
		yesterday_post 			= PostModel.objects.filter(publish_date__day=datetime.today().day - 1).count() # Yesterdays total post
		this_month 				= PostModel.objects.filter(publish_date__month=datetime.today().month).count() # Total posts of this month
		todays_user_post 		= PostModel.objects.filter(user=request.user,publish_date__day=datetime.today().day).count() # Todays posts of users
		yesterday_user_post 	= PostModel.objects.filter(user=request.user,publish_date__day=datetime.today().day - 1).count() # Yesterdays posts of users
		this_month_user_post 	= PostModel.objects.filter(user=request.user,publish_date__month=datetime.today().month).count() # Total posts of users of this month

		# Check total users
		# for i in total_posts:
		# 	print(i.user)

		# Total Users

		user_list = []
		for i in User.objects.all():
			user_list.append(i)


		user1 					= PostModel.objects.filter(user=user_list[0]).count()
		user2 					= PostModel.objects.filter(user=user_list[1]).count()
		user3 					= PostModel.objects.filter(user=user_list[2]).count()


		template_name = "Reporter/dashboard.html"
		context={
			"total_posts":total_posts,
			"user_post":user_post,
			"user_count":user_count,
			"todays_post":todays_post,
			"yesterday_post":yesterday_post,
			"this_month":this_month,
			"todays_user_post":todays_user_post,
			"yesterday_user_post":yesterday_user_post,
			"this_month_user_post":this_month_user_post,
			"user1":user1,
			"user2":user2,
			"user3":user3,

		}

		return render(request,template_name,context)

	# except:

	# 	messages.info(request, "Add atleast 5 posts to view dashboard section.", extra_tags='html_safe')
	# 	return HttpResponseRedirect(reverse('Post:add_new_post'))


def AllUsers(request):

	qs = Profile.objects.all()

	template_name = "Reporter/all_users.html"
	context = {
			"qs":qs
	}

	return render(request,template_name,context)

def UserDetail(request,user=None):

	qs =get_object_or_404(Profile,username=request.user)
	template_name = "Reporter/user_detail.html"
	context = {
			"qs":qs
	}

	return render(request,template_name,context)

def UserUpdate(request,user=None):

	qs =get_object_or_404(Profile,username=request.user)
	form = UserUpdateForm(request.POST or None, request.FILES or None,instance=qs)

	if form.is_valid():
		instance=form.save(commit=False)
		instance.save()
		messages.success(request, "Successfully Updated", extra_tags='html_safe')

	template_name = "Reporter/user_update.html"
	context = {
			"form":form
	}

	return render(request,template_name,context)



def ThemeSettingsEnable(request):

	qs = HomepageMiddleSection.objects.all().count()

	if request.method == "POST" and "enable" in request.POST:

		HomepageMiddleSection.objects.create()
		InsertHeaderFooter.objects.create()
		HomepageMiddleSectionBelow.objects.create()
		HomepageMiddleSectionBelowTwo.objects.create()
		FooterAboveSection.objects.create()
		HomepageAds.objects.create()
		PostDetailPageAds.objects.create()
		CopyRightSection.objects.create()
		InstantArticleModel.objects.create()
		SEO.objects.create()
		messages.success(request,"Successfully Enabled", extra_tags='html_safe')
		return HttpResponseRedirect(reverse('Reporter:enable_settings'))


	template_name = "Reporter/theme_settings_enable.html"
	context = {

				"qs":qs

			}

	return render(request,template_name,context)



def HomepageMiddleSectionWidget(request):

	try:
		qs = HomepageMiddleSection.objects.all()[0]
		form = HomepageMiddleWidgetForm(request.POST or None,instance=qs)

		if qs:

			if form.is_valid():

				instance = form.save(commit=False)
				instance.save()
				messages.success(request,"Successfully Saved", extra_tags='html_safe')

		template_name = "Reporter/middle_widget.html"
		context = {

					"form":form

				}

		return render(request,template_name,context)

	except:

		return HttpResponseRedirect(reverse('Reporter:enable_settings'))


def InsertHeaderFooterView(request):

	try:
		qs = InsertHeaderFooter.objects.all()[0]
		form = InsertHeaderFooterForm(request.POST or None,instance=qs)

		if qs:

			if form.is_valid():

				instance = form.save(commit=False)
				instance.save()
				messages.success(request,"Successfully Saved", extra_tags='html_safe')

		template_name = "Reporter/insert_header_footer.html"
		context = {

					"form":form

				}

		return render(request,template_name,context)

	except:

		return HttpResponseRedirect(reverse('Reporter:enable_settings'))



def HomepageMiddleSectionWidgetBelow(request):

	try:
		qs = HomepageMiddleSectionBelow.objects.all()[0]
		form = HomepageMiddleWidgetFormBelow(request.POST or None,instance=qs)

		if qs:

			if form.is_valid():

				instance = form.save(commit=False)
				instance.save()
				messages.success(request,"Successfully Saved", extra_tags='html_safe')

		template_name = "Reporter/middle_widget_below.html"
		context = {

					"form":form

				}

		return render(request,template_name,context)

	except:

		return HttpResponseRedirect(reverse('Reporter:enable_settings'))



def HomepageMiddleSectionWidgetBelowTwo(request):

	try:
		qs = HomepageMiddleSectionBelowTwo.objects.all()[0]
		form = HomepageMiddleWidgetFormBelowTwo(request.POST or None,instance=qs)

		if qs:

			if form.is_valid():

				instance = form.save(commit=False)
				instance.save()
				messages.success(request,"Successfully Saved", extra_tags='html_safe')

		template_name = "Reporter/middle_widget_below_two.html"
		context = {

					"form":form

				}

		return render(request,template_name,context)

	except:

		return HttpResponseRedirect(reverse('Reporter:enable_settings'))


def FooterAboveSectionView(request):

	try:
		qs = FooterAboveSection.objects.all()[0]
		form = FooterAboveSectionForm(request.POST or None,instance=qs)

		if qs:

			if form.is_valid():

				instance = form.save(commit=False)
				instance.save()
				messages.success(request,"Successfully Saved", extra_tags='html_safe')

		template_name = "Reporter/footer_above.html"
		context = {

					"form":form

				}

		return render(request,template_name,context)

	except:

		return HttpResponseRedirect(reverse('Reporter:enable_settings'))


def GeneralSettingsCreate(request):

	form = GeneralSettingsForm(request.POST or None,request.FILES or None)
	qs = GeneralSettings.objects.all().count()

	if qs == 1:
		return HttpResponseRedirect(reverse('Reporter:general_settings_update'))

	elif qs == 0:
		if form.is_valid():
			instance = form.save(commit=False)
			instance.save()
			messages.success(request,"Successfully Saved", extra_tags='html_safe')
			return HttpResponseRedirect(reverse('Reporter:general_settings_update'))

	template_name = "Reporter/general_settings_create.html"
	context = {

		"form":form
	}

	return render(request,template_name,context)

def GeneralSettingsUpdate(request):

	try:

		qs = GeneralSettings.objects.all()[0]
		form = GeneralSettingsForm(request.POST or None,request.FILES or None,instance=qs)

		if form.is_valid():
			instance = form.save(commit=False)
			instance.save()
			messages.success(request,"Successfully Saved", extra_tags='html_safe')


		template_name = "Reporter/general_settings_update.html"
		context = {

			"form":form,
			"qs":qs
		}

		return render(request,template_name,context)
	except:
		return HttpResponseRedirect(reverse('Reporter:general_settings_create'))


def HomepageAdsSection(request):

	try:

src/templates/Reporter/dashboard-content.html
<div class="col-sm-6 col-lg-3">
   <div class="card text-white bg-flat-color-1">
      <div class="card-body pb-0">
         <h4 class="mb-0">
            <span class="count">{{ total_posts.count }}</span>
         </h4>
         <p class="text-light">Total Posts !</p>
      </div>
   </div>
</div>
<!--/.col-->
<div class="col-sm-6 col-lg-3">
   <div class="card text-white bg-flat-color-2">
      <div class="card-body pb-0">
         <h4 class="mb-0">
            <span class="count">{{ todays_post }}</span>
         </h4>
         <p class="text-light">Todays Posts !</p>
      </div>
   </div>
</div>
<!--/.col-->
<div class="col-sm-6 col-lg-3">
   <div class="card text-white bg-flat-color-3">
      <div class="card-body pb-0">
         <h4 class="mb-0">
            <span class="count">{{ user_post.count }}</span>
         </h4>
         <p class="text-light">My Total Posts ! </p>
      </div>
   </div>
</div>
<!--/.col-->
<div class="col-sm-6 col-lg-3">
   <div class="card text-white bg-flat-color-4">
      <div class="card-body pb-0">
         <h4 class="mb-0">
            <span class="count">{{ user_count.count }}</span>
         </h4>
         <p class="text-light">Total Reporters !</p>
      </div>
   </div>
</div>
<!--/.col-->
<div class="col-xl-12">
   <div class="card">
      <div class="card-body">
         <div class="row">
            <div class="col-sm-6">
               <h4 class="card-title mb-0">Site Performance</h4>
            </div>
            <!--/.col-->
         </div>
         <!--/.row-->
         <hr>
         <div class="chart-wrapper mt-4" >
            <div id="chart_div" style="width: 100%; height: 400px;"></div>
         </div>
      </div>
   </div>
</div>
<div class="col-xl-6">
   <div class="card">
      <div class="card-body">
         <div class="row">
            <div class="col-sm-6">
               <h4 class="card-title mb-0">My Performance</h4>
            </div>
            <!--/.col-->
         </div>
         <!--/.row-->
         <hr>
         <div class="chart-wrapper mt-4" >
            <div id="chart_div2" style="width: 100%; height: 300px;"></div>
         </div>
      </div>
   </div>
</div>
<div class="col-xl-6">
   <div class="card">
      <div class="card-body">
         <div class="row">
            <div class="col-sm-6">
               <h4 class="card-title mb-0">User Performance</h4>
            </div>
            <!--/.col-->
         </div>
         <!--/.row-->
         <hr>
         <div class="chart-wrapper mt-4" >
            <div id="chart_div3" style="width: 100%; height: 300px;"></div>
         </div>
      </div>
   </div>
</div>

src/templates/Reporter/dashboard.html
<!doctype html>
{% load static %}
<html class="no-js" lang="">
   <!--<![endif]-->
   <head>
      <!-- Header -->
      {% include "Reporter/header.html" %} 
      {% include "Reporter/charts.html" %}
   </head>
   <body>
      {% if request.user.is_authenticated %}
      <!-- Navigation-->
      {% include "Reporter/nav-bar.html" %}
      <div class="content mt-3">
         {% block content %}
         {% include "Reporter/dashboard-content.html" %}
         {% endblock %}
      </div>
      <!-- .content -->
      </div><!-- /#right-panel -->
      <!-- Right Panel -->
      <!-- Logout Modal -->
      {% include "Reporter/logout_modal.html" %}
      <!-- Footer Scripts -->
      {% include "Reporter/footer-scripts.html" %}
      {% else %}
      <div class="row">
         <div class="col-sm-12">
            <h1 style="color:red;">You have no permission</h1>
         </div>
      </div>
      {% endif %}
   </body>
</html>

src/templates/Reporter/header.html
   {% load static %}
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin Panel</title>
    <meta name="description" content="Sufee Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="favicon.ico">

    <link rel="stylesheet" href="{% static "AP2/assets/css/normalize.css" %}">
    <link rel="stylesheet" href="{% static "AP2/assets/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "AP2/assets/css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "AP2/assets/css/themify-icons.css" %}">
    <link rel="stylesheet" href="{% static "AP2/assets/css/flag-icon.min.css" %}">
    <link rel="stylesheet" href="{% static "AP2/assets/css/cs-skin-elastic.css" %}">
    <!-- <link rel="stylesheet" href="assets/css/bootstrap-select.less"> -->
    <link rel="stylesheet" href="{% static "AP2/assets/scss/style.css" %}">
    <link href="{% static "AP2/assets/css/lib/vector-map/jqvmap.min.css" %}" rel="stylesheet">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->

src/templates/Reporter/logout_modal.html
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
      <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="{% url "Reporter:user_logout" %}">Logout</a>
          </div>
      </div>
  </div>
</div>

src/templates/Reporter/nav-bar.html
{% load static %}
<!-- Left Panel -->
<aside id="left-panel" class="left-panel">
   <nav class="navbar navbar-expand-sm navbar-default">
      <div class="navbar-header">
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
         <i class="fa fa-bars"></i>
         </button>
         <a class="navbar-brand" href="./">Admin Panel</a>
         <a class="navbar-brand hidden" href="./"><i class="ti-user"></i></a>
      </div>
      <div id="main-menu" class="main-menu collapse navbar-collapse">
         <ul class="nav navbar-nav">
            <li class="active">
               <a href="{{ request.user.get_absolute_url }}"> <i class="menu-icon fa fa-dashboard"></i>Dashboard </a>
            </li>
            <h3 class="menu-title">Post Section</h3>
            <!-- /.menu-title -->
            <li>
               <a href="{% url "Post:post_list" %}"> <i class="menu-icon  ti-layers-alt"></i>All Posts </a>
            </li>
            <li class="menu-item-has-children dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon ti-pin-alt"></i>Add New</a>
               <ul class="sub-menu children dropdown-menu">
                  <li><i class="ti-plus"></i><a href="{% url "Post:add_new_post" %}">Post</a></li>
                  <li><i class="ti-plus"></i><a href="{% url "Post:category_create" %}">Category</a></li>
               </ul>
            </li>
            {% if request.user.is_admin %}
            <h3 class="menu-title">User Management</h3>
            <!-- /.menu-title -->
            <li>
               <a href="{% url "Reporter:user_register" %}"> <i class="menu-icon ti-plus"></i>Add New </a>
            </li>
            <li>
               <a href="{% url "Reporter:reporters" %}"> <i class="menu-icon ti-user"></i>All Reporter </a>
            </li>
            <h3 class="menu-title">Theme Settings</h3>
            <!-- /.menu-title -->
            <li>
               <a href="{% url "Reporter:enable_settings" %}"> <i class="menu-icon  ti-flickr"></i>Enable Settings</a>
            </li>
            <li class="menu-item-has-children dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-columns"></i>Hompage Middle</a>
               <ul class="sub-menu children dropdown-menu">
                  <li><i class="menu-icon ti-plus"></i><a href="{% url "Reporter:middle_widget" %}">Widget One</a></li>
                  <li><i class="menu-icon ti-plus"></i><a href="{% url "Reporter:middle_widget_below" %}">Widget Two</a></li>
                  <li><i class="menu-icon ti-plus"></i><a href="{% url "Reporter:middle_widget_below_two" %}">Widget Three</a></li>
               </ul>
            </li>
            <li class="menu-item-has-children dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon ti-layout"></i>Footer</a>
               <ul class="sub-menu children dropdown-menu">
                  <li><i class="menu-icon ti-plus"></i><a href="{% url "Reporter:footer_above" %}">Footer One</a></li>
                  <li><i class="menu-icon ti-plus"></i><a href="#">Footer Two</a></li>
                  <li><i class="menu-icon ti-plus"></i><a href="#">Footer Three</a></li>
               </ul>
            </li>
            <h3 class="menu-title">Tools</h3>
            <!-- /.menu-title -->
            <li>
               <a href="{% url "Reporter:insert_header" %}"> <i class="menu-icon  fa fa-code"></i>Insert Header & Footer</a>
            </li>
             <h3 class="menu-title">Site Settings</h3>
            <!-- /.menu-title -->
             <li>
               <a href="{% url "Reporter:general_settings_create" %}"> <i class="menu-icon  fa fa-wrench"></i>General Settings</a>
            </li>
            <li>
               <a href="{% url "Reporter:copyright_section" %}"> <i class="menu-icon  fa fa-laptop"></i>Copyright Section</a>
            </li>
            <h3 class="menu-title">Ads Management</h3>
            <!-- /.menu-title -->
            <li>
               <a href="{% url "Reporter:homepage_ads" %}"> <i class="menu-icon  fa fa-laptop"></i>Hompage Ads</a>
            </li>
            <li>
               <a href="{% url "Reporter:post_detail_ads" %}"> <i class="menu-icon  fa fa-laptop"></i>Post Detail Ads</a>
            </li>
            <h3 class="menu-title">Facebook Instant Article</h3>
            <!-- /.menu-title -->
            <li>
               <a href="{% url "Reporter:insatnt_article" %}"> <i class="menu-icon  fa fab fa-facebook"></i>Setup Instant Article</a>
            </li>
            <h3 class="menu-title">SEO</h3>
            <!-- /.menu-title -->
            <li>
               <a href="{% url "Reporter:seo_settings" %}"> <i class="menu-icon  fa fas fa-globe"></i>SEO Settings</a>
            </li>
            {% endif %}
            <h3 class="menu-title">Profile Settings</h3>
            <!-- /.menu-title -->
            <li>
               <a href="{% url "Reporter:user_detail" request.user %}"> <i class="menu-icon ti-id-badge"></i>Detail</a>
            </li>
            <li>
               <a href="{% url "Reporter:user_update" request.user %}"> <i class="menu-icon fa fa-edit"></i>Update</a>
            </li>
         </ul>
      </div>
      <!-- /.navbar-collapse -->
   </nav>
</aside>
<!-- /#left-panel -->
<!-- Left Panel -->
<!-- Right Panel -->
<div id="right-panel" class="right-panel">
<!-- Header-->
<header id="header" class="header">
   <div class="header-menu">
      <div class="col-sm-7">
         <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
         <div class="header-left">
            <p><i class="fa fa-user"> </i>  {{ request.user }}</p>
         </div>
      </div>
      <div class="col-sm-5">
         <div class="user-area dropdown float-right">
            <p><i class="fa  fa-sign-out"> </i>  <a data-toggle="modal" data-target="#logoutModal" href="#">Logout</a></p>
         </div>
      </div>
   </div>
</header>
<!-- /header -->
<!-- Header-->